name: Dash Enterprise Deploy
description: Dash Enterprise Deploy
inputs:
  DE_PASSWORD:
    required: true
  DE_HOST:
    required: true
  DE_USERNAME:
    required: true
  GH_ACCESS_TOKEN:
    description: Github Personal Access token with permissions set to "repo".
    required: true
  app_name:
    required: false
    type: string
  app_directory:
    required: false
    default: ${{ github.workspace }}
  timeout:
    required: false
    default: 300
    
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dekn-client
      shell: bash
      run: |
        git config --global url."https://${GH_ACCESS_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
        python -m pip install --upgrade pip
        pip install git+https://github.com/plotly/dekn-client.git
      env:
        GH_ACCESS_TOKEN: ${{ inputs.GH_ACCESS_TOKEN }}
    - name: Generate app name
      id: app_name
      shell: bash
      run: |
        # If an app name is not provided, use the repository name as the app name
        if [ -z "$APP_NAME" ]; then
            repository="$GITHUB_REPOSITORY"
            APP_NAME=${repository#*/}
        fi
        # Add the PR number as a suffix for deploy previews
        if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
            sep="-"
            APP_NAME=$APP_NAME-$EVENT_NUMBER
        fi
        echo "::set-output name=app_name::$APP_NAME"
      env:
        APP_NAME: ${{ inputs.app_name }}
        EVENT_NUMBER: ${{github.event.number}}
    - name: Inject code and deploy
      shell: bash
      if: github.event.action != 'closed'
      run: |
        dekn deploy . --name ${{ steps.app_name.outputs.app_name }} -fv
      env:
        DASH_ENTERPRISE_HOST: ${{inputs.DE_HOST}}
        DASH_ENTERPRISE_PASSWORD: ${{inputs.DE_PASSWORD}}
        DASH_ENTERPRISE_USERNAME: ${{inputs.DE_USERNAME}}
    - name: Generate details link as commit status
      shell: bash
      if: github.event.action != 'closed'
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json"\
          -H "Authorization: Bearer ${{inputs.GH_ACCESS_TOKEN}}"\
          -H "X-GitHub-Api-Version: 2022-11-28"\
          https://api.github.com/repos/${{ github.repository }}/statuses/${{github.event.pull_request.head.sha || github.sha}}\
          -d '{"state":"success","target_url":"https://${{ inputs.DE_HOST }}/apps/${{ steps.app_name.outputs.app_name }}","description":"App manager ready!","context":"deploy/${{ steps.app_name.outputs.app_name }}"}'
    - name: Await build status
      shell: bash
      run: ${{ github.action_path }}/await_deploy_status.sh
      env:
        DE_HOST: ${{inputs.DE_HOST}}
        DE_PASSWORD: ${{inputs.DE_PASSWORD}}
        DE_USERNAME: ${{inputs.DE_USERNAME}}
        TIMEOUT: ${{ inputs.timeout }}
        APP_NAME: ${{ steps.app_name.outputs.app_name }}
    - name: Remove staging application
      shell: bash
      if: github.event.action == 'closed'
      run: |
        dekn apps delete --name ${{ steps.app_name.outputs.app_name }}
      env:
        DE_PASSWORD: ${{inputs.DE_PASSWORD}}
        DE_HOST: ${{inputs.DE_HOST}}
        DE_USERNAME: ${{inputs.DE_USERNAME}}


branding:
  icon: activity
  color: purple